### ISSUE TITLE
Error at Section 2 Step 1

### ISSUE THREAD

**Issue by pptnz** [ChengxiangQiu/tome_code#2]
Hi, thank you for sharing the code implementation! I have a question on Section 2 step 1.

I want to plot the Fig. 2c (directed acyclic graph of cellular trajectories) in the paper. I am trying to run the Section 2 Step 1. I got error at line 52. I tried different kk, 1, 2, 3, and 4, but consistently got the error.
` Error in idx[i, ] <- res[[i]][[1]] : 
  number of items to replace is not a multiple of replacement length `

1. I wonder if you have encountered these issues. I think this might be due to the Seurat version. I wonder which Seurat version you have used to develop. 
2. I want to double check that the heat map in the Section 2 step 3 is corresponding to the Fig. 2c (tree structure). If not, is there a code implementation to plot the tree?
3. Also, I wonder if you could share the rds files to create the tree structure (i.e. edge_all.rds file). 

Thank you!

**Comment by ChengxiangQiu** [comment]
Thanks for your questions.
1. I used Seurat/v3.2.3. 
2. The tree structure plot was created using D3.js. Basically, it uses the JSON format profile as input to make such a plot. I am glad to share the JSON profile if you need.
3. Yes, could you send me an email (cxqiu@uw.edu)? I will send you the data by email.

**Comment by pptnz** [comment]
I really appreciate your kind help! I sent you an email.
