### ISSUE TITLE
Query about cellular trajectories

### ISSUE THREAD

**Issue by EternalEnvy10** [ChengxiangQiu/tome_code#3]
Hi Chengxiang,

Your work is fantastic and has given us a lot of inspiration for our own projects. 

I have a question, when I am repeating your process, in section2 I find that the script of step3 ends up with a heatmap between two periods, how do I get the cell trajectory map as you show in the article figure2c?

Looking forward to your reply

Best,
Zhaonian

**Comment by ZJ-zuojing** [comment]
Hi Chengxiang, 

I also have the same question as @EternalEnvy10  does.

looking forward to your reply!

Best,
Zuojing

**Comment by ChengxiangQiu** [comment]
Sorry for the confusion. I just uploaded two profiles in the "help_code" folder. 
1) create_map.py, which will help you create a JSON format file as the data input of the D3.js script. It requires the "mouse_edge" and "edge_prob" files as input.
2) map.html, which is a html/javascript format (D3.js) file, you could replace the JSON format input (line 36) with the one generated by the above script.
Please let me know if any questions.

**Comment by EternalEnvy10** [comment]
Hi Chengxiang,

Sorry for taking so long to reply to you and thank you for the uploaded code.
Thanks again for your enthusiastic help!

Best,
Zhaonian

**Comment by vagabond12** [comment]
> Sorry for the confusion. I just uploaded two profiles in the "help_code" folder.
> 
> 1. create_map.py, which will help you create a JSON format file as the data input of the D3.js script. It requires the "mouse_edge" and "edge_prob" files as input.
> 2. map.html, which is a html/javascript format (D3.js) file, you could replace the JSON format input (line 36) with the one generated by the above script.
>    Please let me know if any questions.

Hi Chengxiang,
Is there a method to show the name for the nodes? As for new data, we do not know that the nodes indicate.
Thank you very much.
