### ISSUE TITLE
Query about the order of cluster in cell trajectory map

### ISSUE THREAD

**Issue by EternalEnvy10** [ChengxiangQiu/tome_code#4]
Hi Chengxiang,

I'm sorry to bother you again. I have successfully completed the plot of the Cell Trajectory Map using the script you updated last time. This is a really cool picture, by the way. I also want to make some adjustments to the map, such as sorting by custom cluster, now, which is sorted by the number of clusters from smallest to largest.

Looking forward your reply.

Best,
Zhaonian

**Comment by ChengxiangQiu** [comment]
Hi Zhaonian,

I am sure if I really understand your question, but I guess you want to sort the items in that plot. First, you need to set the order of items in the JSON data (e.g. ranging from 1 to ...), I used keyword "fx" in my JSON data. Then, in the html file, there is one line "nodes.forEach(function(d) { d.x = d.fx * 12; });", which will help you to set the coordinate of each item. I hope it helps.

**Comment by EternalEnvy10** [comment]
> 
Thank you very much for your help. Your advice helped me to solve my problem easily :)

Thanks again for your reply!
