### ISSUE TITLE
Query about scripts for candidate key TF in Fig.5

### ISSUE THREAD

**Issue by EternalEnvy10** [ChengxiangQiu/tome_code#5]
Hi Chengxiang,

It's me asking you a question again:)

When drawing a cellular trajectory plot, you generously provide a javascript script. Is there a similar script for plotting the figure of Fig5d?

Best,
Zhaonian

**Comment by ChengxiangQiu** [comment]
I am afraid not. The figure 5d was manually created using Adobe Illustrator.

**Comment by EternalEnvy10** [comment]
Ok, thanks for your reply.
